# Generated by Django 5.2.6 on 2025-09-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
